version: '3'
services:
  dbt:
  live_py:
    build: .
    restart: unless-stopped
    volumes:
      - './:/app/'
    ports:
      - "8080:5008"
#    depends_on:
#      - db
    networks: 
      - webserver-net

networks:
  webserver-net:
    external: true
