version: '3'

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd.user:/etc/apache2/.htpasswd
      - ./nginx/.htpasswd.go:/etc/apache2/.htpasswd.go
      - ${HOME}/certbot/conf:/etc/letsencrypt
      - ${HOME}/certbot/www:/var/www/certbot
      - ../../docs/html:/var/www/html
      - ${HOME}/log:/var/log
    ports:
      - "80:80"
      - "443:443"
    networks:
      - traefik-net

  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ${HOME}/certbot/conf:/etc/letsencrypt
      - ${HOME}/certbot/www:/var/www/certbot
      - ${HOME}/log/:/var/log/
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - traefik-net

  php-app:
    build:
      context: php/
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ../../docs/html:/var/www/html
      - ./php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    working_dir: /var/www/html
    networks:
      - traefik-net

networks:
  traefik-net:
    external: true

