version: '3'
#https://rmoff.net/2018/08/02/kafka-listeners-explained/
#https://www.kaaiot.com/blog/kafka-docker
##########################Kafka#########################
# Each Kafka listener will be confgiured for each ip/domain with a unique port #
# ex localhost:port will have local host access to docker container and external host services
# ex kafka:port will only have access internally to all containers within a same network #
# ex ip:port will have external access from other host to this host #

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - 2181:2181
    volumes:
      - zk-data:/var/lib/zookeeper/data # for Data
      - zk-txn-logs:/var/lib/zookeeper/log # for transaction logs
    networks:
      - traefik-net

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    environment:
      # KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      # KAFKA_LISTENERS: PLAINTEXT://:9092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      # LISTENER_1://localhost:29092,LISTENER_2://10.138.154.16:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "29092:29092"
      - "9999:9999"
      #- 29092:29092 uncomment for multiple listeners and add more ports for each listener
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - traefik-net

volumes:
  kafka-data:
    #driver: local
    #driver_opts:
      #o: bind
      #type: none
      #device: /var/db/kafka/data
  zk-data:
    #driver: local
    #driver_opts:
    #o: bind
    #type: none
    #device: /var/db/zk/data
  zk-txn-logs:
   #driver: local
   #driver_opts:
     #o: bind
     #type: none
     #device: /var/db/zk/txn-logs

networks:
  traefik-net:
    external: true
