#https://rmoff.net/2018/08/02/kafka-listeners-explained/
#https://www.kaaiot.com/blog/kafka-docker
#https://limascloud.com/2022/01/02/docker-compose-kafka-setup-confluent-cloud/
---
version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # ports:
    #   - "2181:2181"
    volumes:
      - zk-data:/var/lib/zookeeper/data # for Data
      - zk-txn-logs:/var/lib/zookeeper/log # for transaction logs
    networks:
      - webserver-net

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      # KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093,PLAINTEXT_HOST://localhost:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,OUTSIDE://host.docker.internal:9092
      KAFKA_LISTENERS: INTERNAL://:9093,OUTSIDE://:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_RETENTION_MS: 604800000
      KAFKA_RETENTION_BYTES: -1
    extra_hosts:
      - "host.docker.internal:172.0.0.1"
      # - "localhost:172..0.1"
    depends_on:
      - zookeeper
    ports:
      - "127.0.0.1:9092:9092"
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - webserver-net

  kafka-ui:
    #image: confluentinc/cp-enterprise-control-center:latest
    image: docker.redpanda.com/vectorized/console:latest
    #hostname: control-center
    depends_on:
      - kafka
    # ports:
    #   # - "9021:9021"
    #   - "127.0.0.1:9021:8080"
    environment:
      #CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9093'
      #CONTROL_CENTER_REPLICATION_FACTOR: 1
      KAFKA_BROKERS: 'kafka:9093'
      #KAFKA_TLS_ENABLED: true
      #KAFKA_SASL_ENABLED: true
      #KAFKA_SASL_USERNAME: ""
      #KAFKA_SASL_PASSWORD: ""
      PORT: 9021
    networks:
      - webserver-net
  
volumes:
  kafka-data:

  zk-data:

  zk-txn-logs:
    
networks:
  webserver-net:
    external: true
