version: "3.5"

services:
  live_kafka_ws_pubsub:
    image: registry.gitlab.com/lightmeter/kafka-websocket-simple-adaptor:latest
    restart: unless-stopped
    environment:
      LISTEN_ADDRESS: ":5007"
      BROKER_ADDRESS: "kafka:9093"
      MAX_MESSAGE_SIZE: "10485760" # 10MB
    networks:
      - traefik-net

networks:
  traefik-net:
