global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: py_live
    static_configs:
      - targets: ['172.0.0.1:5005']
  - job_name: go_ingest
    static_configs:
      - targets: ['172.0.0.1:5006']
  - job_name: traefik
    static_configs:
      - targets: ['172.0.0.1:8080']

