#cloud-config

users:
  - name: admin
    ssh-authorized-keys: []
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash

write_files:
  - path: /etc/ssh/sshd_config.d/01-lightmeter.conf
    permissions: "0644"
    content: |
      AllowUsers admin
      PermitRootLogin no
      Port 2223
      PasswordAuthentication no
  - path: /etc/apt/sources.list.d/docker.list
    permissions: "0644"
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian  bullseye stable
  - path: /etc/apt/apt.conf.d/50unattended-upgrades
    permissions: "0644"
    content: |
      Unattended-Upgrade::Origins-Pattern {
        "origin=Debian,codename=${distro_codename},label=Debian";
        "origin=Debian,codename=${distro_codename},label=Debian-Security";
      };
      Unattended-Upgrade::Package-Blacklist {
      };
      Unattended-Upgrade::Mail "hello@lightmeter.io";
  - path: /etc/apt/apt.conf.d/20auto-upgrades
    permissions: "0644"
    content: |
      APT::Periodic::Update-Package-Lists "1";
      APT::Periodic::Unattended-Upgrade "1";
  - path: /etc/docker/daemon.json
    permissions: "0644"
    content: |
      {
        "log-driver": "local",
        "log-opts": {
          "max-size": "1024m"
        }
      }

runcmd:
  - DEBIAN_FRONTEND=noninteractive apt update -y
  - DEBIAN_FRONTEND=noninteractive apt upgrade -y
  - DEBIAN_FRONTEND=noninteractive apt install -y curl gpg htop vim nmon ripgrep unattended-upgrades apt-listchanges bsd-mailx rsync
  - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
  - apt update -y
  - apt install -y docker-ce docker-ce-cli containerd.io
  - mkdir -p /usr/local/libexec/docker/cli-plugins/
  - curl -L https://github.com/docker/compose/releases/download/v2.11.2/docker-compose-linux-x86_64 > /usr/local/libexec/docker/cli-plugins/docker-compose
  - chmod a+x /usr/local/libexec/docker/cli-plugins/docker-compose
  - usermod -a -G docker admin
  - dd if=/dev/zero of=/file.swap bs=4M count=1024
  - chmod 0600 /file.swap
  - mkswap /file.swap
  - echo "/file.swap swap swap defaults 0 0" >> /etc/fstab
  - systemctl reboot

