entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: lets-encrypt
        domains:
          - main: "storage.lightmeter.io"
            sans:
              - "metabase.storage.lightmeter.io"
              - "docker.storage.lightmeter.io"
              - "ingest.storage.lightmeter.io"
              - "metrics.storage.lightmeter.io"
              - "interface.storage.lightmeter.io"

certificatesResolvers:
  lets-encrypt:
    acme:
      email: "admin@lightmeter.io"
      storage: "acme.json"
      tlsChallenge: {}
      httpChallenge:
        entryPoint: web

            
api:
  dashboard: true
  insecure: true

providers:
  docker: true

log:
  level: "error"

accessLog:
  filePath: "/logs/traefik-access.log"
  format: json
  bufferingSize: 100

accesslog: true

metrics:
  prometheus: {}

http:
  middlewares:
    simpleAuth:
      basicAuth:
        users: ["admin:$apr1$8Y4INeOi$dd.TYrzzG.EvLYOVKXMnu0"]
