STATE_COLORS = {
    "deferred": "mediumpurple",
    "failed": "firebrick",
    "queued": "darkgray",
    "removed": "lightgrey",
    "restarting": "violet",
    "running": "#01FF70",
    "scheduled": "tan",
    "shutdown": "blue",
    "skipped": "darkorchid",
    "success": "#2ECC40",
    "up_for_reschedule": "turquoise",
    "up_for_retry": "yellow",
    "upstream_failed": "orange",
}
